
LL =['AYLMNKVVNVVEGKV', 'CDILCHWCKRNVGWK', 'CHWCKRNVGWKYLQS', 'CKRNVGWKYLQSSND','CRHCKTHLSSSFQII','DDQQYKEGKFILELK','DILCHWCKRNVGWKY','DQQYKEGKFILELKN','DYLVCDILCHWCKRN','DYRGRTGTAYLMNKV','EGKFILELKNICKCT','ENPLSSPSSSYKSIN','EQRRMLTGDYLVCDI','FHSQHRSQKNVSFIT','FITYGCRHCKTHLSS','GDYLVCDILCHWCKR','GKVEQRRMLTGDYLV','GLRYSIYIENPLSSP','GRTGTAYLMNKVVNV','GTAYLMNKVVNVVEG','HCKTHLSSSFQIISR','HLSSSFQIISRDYRG','IISRDYRGRTGTAYL','ISRDYRGRTGTAYLM','ITYGCRHCKTHLSSS','IYIENPLSSPSSSYK','KEGKFILELKNICKC','KRNVGWKYLQSSNDD','KSINDPLFHSQHRSQ','KVEQRRMLTGDYLVC','KVVNVVEGKVEQRRM','KYLQSSNDDQQYKEG','LFHSQHRSQKNVSFI','LMNKVVNVVEGKVEQ','LQSSNDDQQYKEGKF','LSSPSSSYKSINDPL','LSSSFQIISRDYRGR','LTGDYLVCDILCHWC','LVCDILCHWCKRNVG','MGLRYSIYIENPLSS','MNKVVNVVEGKVEQR','NDDQQYKEGKFILEL','NDPLFHSQHRSQKNV','NKVVNVVEGKVEQRR','NPLSSPSSSYKSIND','NVVEGKVEQRRMLTG','PLSSPSSSYKSINDP','PSSSYKSINDPLFHS','QHRSQKNVSFITYGC','QIISRDYRGRTGTAY','QKNVSFITYGCRHCK','QYKEGKFILELKNIC','RDYRGRTGTAYLMNK','RGRTGTAYLMNKVVN','RHCKTHLSSSFQIIS','RMLTGDYLVCDILCH','RRMLTGDYLVCDILC','RSQKNVSFITYGCRH','RTGTAYLMNKVVNVV','RYSIYIENPLSSPSS','SFITYGCRHCKTHLS','SINDPLFHSQHRSQK','SIYIENPLSSPSSSY','SPSSSYKSINDPLFH','SQHRSQKNVSFITYG','SQKNVSFITYGCRHC','SRDYRGRTGTAYLMN','SSFQIISRDYRGRTG','SSNDDQQYKEGKFIL','FQIISRDYRGRTGTA','SSPSSSYKSINDPLF','SSSFQIISRDYRGRT','SSSYKSINDPLFHSQ','SSYKSINDPLFHSQH','SYKSINDPLFHSQHR','TAYLMNKVVNVVEGK','TGTAYLMNKVVNVVE','THLSSSFQIISRDYR','TYGCRHCKTHLSSSF','VCDILCHWCKRNVGW','VGWKYLQSSNDDQQY','VNVVEGKVEQRRMLT','VSFITYGCRHCKTHL','VVEGKVEQRRMLTGD','VVNVVEGKVEQRRML','WKYLQSSNDDQQYKE','YGCRHCKTHLSSSFQ','YKEGKFILELKNICK','YKSINDPLFHSQHRS','YLMNKVVNVVEGKVE','YLQSSNDDQQYKEGK','YLVCDILCHWCKRNV','YRGRTGTAYLMNKVV','YSIYIENPLSSPSSS','MLTGDYLVCDILCHW']
L = ['AANLAQGHQSRPHQR','AHSHSYTPTSSQPRP','ANLAQGHQSRPHQRP','APQNNVVSAPTYYTN','APTYYTNYTMPVYTN','AQGHQSRPHQRPSTM','ATSSSQTYAHSHSYT','AWQGNRPLYVQPGDP','CGECRGSGRTRFLLD','CKSCWRRFAPQNNVV','CRGSGRTRFLLDEDI','CSKCGNTGYKLKNGR','DDELPSYEDVIKEEE','DEDICPLCHGVGRII','DICPLCHGVGRIITQ','DTHDDELPSYEDVIK','DVIKEEERLQSQPPR','ECRGSGRTRFLLDED','EDICPLCHGVGRIIT','EDVIKEEERLQSQPP','ELPSYEDVIKEEERL','FLLDEDICPLCHGVG','FYCSKCGNTGYKLKN','GDPRLGGVLCGECRG','GECRGSGRTRFLLDE','GGVLCGECRGSGRTR','GHQSRPHQRPSTMPA','GNRPLYVQPGDPRLG','GNTGYKLKNGRSCKS','GRSCKSCWRRFAPQN','GRTRFLLDEDICPLC','GSGRTRFLLDEDICP','GVLCGECRGSGRTRF','GYKLKNGRSCKSCWR','HDDELPSYEDVIKEE','HQSRPHQRPSTMPAT','HSHSYTPTSSQPRPP','HSYTPTSSQPRPPPR','ICPLCHGVGRIITQP','IKEEERLQSQPPRPP','KCGNTGYKLKNGRSC','KDTHDDELPSYEDVI','KLKNGRSCKSCWRRF','KNGRSCKSCWRRFAP','KSCWRRFAPQNNVVS','LAQGHQSRPHQRPST','LCHGVGRIITQPQRY','LDEDICPLCHGVGRI','LGGVLCGECRGSGRT','LKNGRSCKSCWRRFA','LLDEDICPLCHGVGR','LPSYEDVIKEEERLQ','LPWTYPPRFYCSKCG','LQSQPPRPPRPAANL','LYVQPGDPRLGGVLC','MPATSSSQTYAHSHS','MPVYTNAWQGNRPLY','MSKDTHDDELPSYED','NAWQGNRPLYVQPGD','NGRSCKSCWRRFAPQ','NNVVSAPTYYTNYTM','NPSLPWTYPPRFYCS','NRPLYVQPGDPRLGG','NTGYKLKNGRSCKSC','NYTMPVYTNAWQGNR','PAANLAQGHQSRPHQ','PGDPRLGGVLCGECR','PHQRPSTMPATSSSQ','PLCHGVGRIITQPQR','PLYVQPGDPRLGGVL','PPPRPQQNPSLPWTY','PPRFYCSKCGNTGYK','PPRPAANLAQGHQSR','PPRPPRPAANLAQGH','PPRPQQNPSLPWTYP','PQQNPSLPWTYPPRF','PRFYCSKCGNTGYKL','PRLGGVLCGECRGSG','PRPAANLAQGHQSRP','PRPPPRPQQNPSLPW','PRPPRPAANLAQGHQ','PRPQQNPSLPWTYPP','PSLPWTYPPRFYCSK','PSYEDVIKEEERLQS','PTSSQPRPPPRPQQN','PTYYTNYTMPVYTNA','PVYTNAWQGNRPLYV','PWTYPPRFYCSKCGN','QGHQSRPHQRPSTMP','QGNRPLYVQPGDPRL','QNNVVSAPTYYTNYT','QNPSLPWTYPPRFYC','QPGDPRLGGVLCGEC','QPPRPPRPAANLAQG','QPRPPPRPQQNPSLP','QSQPPRPPRPAANLA','QSRPHQRPSTMPATS','QTYAHSHSYTPTSSQ','RFAPQNNVVSAPTYY','RFLLDEDICPLCHGV','RFYCSKCGNTGYKLK','RGSGRTRFLLDEDIC','RLGGVLCGECRGSGR','RLQSQPPRPPRPAAN','RPAANLAQGHQSRPH','RPHQRPSTMPATSSS','RPLYVQPGDPRLGGV','RPPRPAANLAQGHQS','RPQQNPSLPWTYPPR','RPSTMPATSSSQTYA','RSCKSCWRRFAPQNN','SCKSCWRRFAPQNNV','SCWRRFAPQNNVVSA','SGRTRFLLDEDICPL','SHSYTPTSSQPRPPP','SKCGNTGYKLKNGRS','SLPWTYPPRFYCSKC','SQPPRPPRPAANLAQ','SQPRPPPRPQQNPSL','SQTYAHSHSYTPTSS','SRPHQRPSTMPATSS','SSQTYAHSHSYTPTS','SSSQTYAHSHSYTPT','STMPATSSSQTYAHS','SYEDVIKEEERLQSQ','SYTPTSSQPRPPPRP','TGYKLKNGRSCKSCW','THDDELPSYEDVIKE','TMPVYTNAWQGNRPL','TNAWQGNRPLYVQPG','TNYTMPVYTNAWQGN','TRFLLDEDICPLCHG','TSSQPRPPPRPQQNP','TSSSQTYAHSHSYTP','TYAHSHSYTPTSSQP','TYPPRFYCSKCGNTG','TYYTNYTMPVYTNAW','VIKEEERLQSQPPRP','VQPGDPRLGGVLCGE','VSAPTYYTNYTMPVY','VVSAPTYYTNYTMPV','VYTNAWQGNRPLYVQ','WQGNRPLYVQPGDPR','WTYPPRFYCSKCGNT','YAHSHSYTPTSSQPR','YCSKCGNTGYKLKNG','YEDVIKEEERLQSQP','YKLKNGRSCKSCWRR','YTMPVYTNAWQGNRP','YTNAWQGNRPLYVQP','YTNYTMPVYTNAWQG','LCHGVGRIITQPQRY','YTPTSSQPRPPPRPQ','YVQPGDPRLGGVLCG','YYTNYTMPVYTNAWQ']


next={}
for s in LL:                        
  for i in range(0,len(s)-4):     # taking all elements in LL and creating a dictionary of all possible four letter sequences with the subsequent fifth letter becoming the entry value
    next[s[i:i+4]]=s[i+4]

begin="MGLR"                      # the beginning four letters of sequence is assumed as given
seq=begin

while True:
      if begin in next:           # continue concatenating letters after each four letter sequence until you reach the end
         n=next[begin]
         seq=seq+n
         begin=begin[1:4]+n
      else:
       break

print seq                         # print final sequence
      
'''when using L as the entries, this code DOES NOT work and only prints out "MGLR" at the end. 
This is because MGLR is not in the next dictionary created from L (meaning MGLR is not part of the solution sequence for L)
HOWEVER, even when putting the correct beginning sequence "MSKD" the sequence still comes up with some errors
I am currently trying to figure out why there's an error
 '''
