#L =['AYLMNKVVNVVEGKV', 'CDILCHWCKRNVGWK', 'CHWCKRNVGWKYLQS', 'CKRNVGWKYLQSSND','CRHCKTHLSSSFQII','DDQQYKEGKFILELK','DILCHWCKRNVGWKY','DQQYKEGKFILELKN','DYLVCDILCHWCKRN','DYRGRTGTAYLMNKV','EGKFILELKNICKCT','ENPLSSPSSSYKSIN','EQRRMLTGDYLVCDI','FHSQHRSQKNVSFIT','FITYGCRHCKTHLSS','GDYLVCDILCHWCKR','GKVEQRRMLTGDYLV','GLRYSIYIENPLSSP','GRTGTAYLMNKVVNV','GTAYLMNKVVNVVEG','HCKTHLSSSFQIISR','HLSSSFQIISRDYRG','IISRDYRGRTGTAYL','ISRDYRGRTGTAYLM','ITYGCRHCKTHLSSS','IYIENPLSSPSSSYK','KEGKFILELKNICKC','KRNVGWKYLQSSNDD','KSINDPLFHSQHRSQ','KVEQRRMLTGDYLVC','KVVNVVEGKVEQRRM','KYLQSSNDDQQYKEG','LFHSQHRSQKNVSFI','LMNKVVNVVEGKVEQ','LQSSNDDQQYKEGKF','LSSPSSSYKSINDPL','LSSSFQIISRDYRGR','LTGDYLVCDILCHWC','LVCDILCHWCKRNVG','MGLRYSIYIENPLSS','MNKVVNVVEGKVEQR','NDDQQYKEGKFILEL','NDPLFHSQHRSQKNV','NKVVNVVEGKVEQRR','NPLSSPSSSYKSIND','NVVEGKVEQRRMLTG','PLSSPSSSYKSINDP','PSSSYKSINDPLFHS','QHRSQKNVSFITYGC','QIISRDYRGRTGTAY','QKNVSFITYGCRHCK','QYKEGKFILELKNIC','RDYRGRTGTAYLMNK','RGRTGTAYLMNKVVN','RHCKTHLSSSFQIIS','RMLTGDYLVCDILCH','RRMLTGDYLVCDILC','RSQKNVSFITYGCRH','RTGTAYLMNKVVNVV','RYSIYIENPLSSPSS','SFITYGCRHCKTHLS','SINDPLFHSQHRSQK','SIYIENPLSSPSSSY','SPSSSYKSINDPLFH','SQHRSQKNVSFITYG','SQKNVSFITYGCRHC','SRDYRGRTGTAYLMN','SSFQIISRDYRGRTG','SSNDDQQYKEGKFIL','FQIISRDYRGRTGTA','SSPSSSYKSINDPLF','SSSFQIISRDYRGRT','SSSYKSINDPLFHSQ','SSYKSINDPLFHSQH','SYKSINDPLFHSQHR','TAYLMNKVVNVVEGK','TGTAYLMNKVVNVVE','THLSSSFQIISRDYR','TYGCRHCKTHLSSSF','VCDILCHWCKRNVGW','VGWKYLQSSNDDQQY','VNVVEGKVEQRRMLT','VSFITYGCRHCKTHL','VVEGKVEQRRMLTGD','VVNVVEGKVEQRRML','WKYLQSSNDDQQYKE','YGCRHCKTHLSSSFQ','YKEGKFILELKNICK','YKSINDPLFHSQHRS','YLMNKVVNVVEGKVE','YLQSSNDDQQYKEGK','YLVCDILCHWCKRNV','YRGRTGTAYLMNKVV','YSIYIENPLSSPSSS','MLTGDYLVCDILCHW']


L = ['AANLAQGHQSRPHQR','AHSHSYTPTSSQPRP','ANLAQGHQSRPHQRP','APQNNVVSAPTYYTN','APTYYTNYTMPVYTN','AQGHQSRPHQRPSTM','ATSSSQTYAHSHSYT','AWQGNRPLYVQPGDP','CGECRGSGRTRFLLD','CKSCWRRFAPQNNVV','CRGSGRTRFLLDEDI','CSKCGNTGYKLKNGR','DDELPSYEDVIKEEE','DEDICPLCHGVGRII','DICPLCHGVGRIITQ','DTHDDELPSYEDVIK','DVIKEEERLQSQPPR','ECRGSGRTRFLLDED','EDICPLCHGVGRIIT','EDVIKEEERLQSQPP','ELPSYEDVIKEEERL','FLLDEDICPLCHGVG','FYCSKCGNTGYKLKN','GDPRLGGVLCGECRG','GECRGSGRTRFLLDE','GGVLCGECRGSGRTR','GHQSRPHQRPSTMPA','GNRPLYVQPGDPRLG','GNTGYKLKNGRSCKS','GRSCKSCWRRFAPQN','GRTRFLLDEDICPLC','GSGRTRFLLDEDICP','GVLCGECRGSGRTRF','GYKLKNGRSCKSCWR','HDDELPSYEDVIKEE','HQSRPHQRPSTMPAT','HSHSYTPTSSQPRPP','HSYTPTSSQPRPPPR','ICPLCHGVGRIITQP','IKEEERLQSQPPRPP','KCGNTGYKLKNGRSC','KDTHDDELPSYEDVI','KLKNGRSCKSCWRRF','KNGRSCKSCWRRFAP','KSCWRRFAPQNNVVS','LAQGHQSRPHQRPST','LCHGVGRIITQPQRY','LDEDICPLCHGVGRI','LGGVLCGECRGSGRT','LKNGRSCKSCWRRFA','LLDEDICPLCHGVGR','LPSYEDVIKEEERLQ','LPWTYPPRFYCSKCG','LQSQPPRPPRPAANL','LYVQPGDPRLGGVLC','MPATSSSQTYAHSHS','MPVYTNAWQGNRPLY','MSKDTHDDELPSYED','NAWQGNRPLYVQPGD','NGRSCKSCWRRFAPQ','NNVVSAPTYYTNYTM','NPSLPWTYPPRFYCS','NRPLYVQPGDPRLGG','NTGYKLKNGRSCKSC','NYTMPVYTNAWQGNR','PAANLAQGHQSRPHQ','PGDPRLGGVLCGECR','PHQRPSTMPATSSSQ','PLCHGVGRIITQPQR','PLYVQPGDPRLGGVL','PPPRPQQNPSLPWTY','PPRFYCSKCGNTGYK','PPRPAANLAQGHQSR','PPRPPRPAANLAQGH','PPRPQQNPSLPWTYP','PQQNPSLPWTYPPRF','PRFYCSKCGNTGYKL','PRLGGVLCGECRGSG','PRPAANLAQGHQSRP','PRPPPRPQQNPSLPW','PRPPRPAANLAQGHQ','PRPQQNPSLPWTYPP','PSLPWTYPPRFYCSK','PSYEDVIKEEERLQS','PTSSQPRPPPRPQQN','PTYYTNYTMPVYTNA','PVYTNAWQGNRPLYV','PWTYPPRFYCSKCGN','QGHQSRPHQRPSTMP','QGNRPLYVQPGDPRL','QNNVVSAPTYYTNYT','QNPSLPWTYPPRFYC','QPGDPRLGGVLCGEC','QPPRPPRPAANLAQG','QPRPPPRPQQNPSLP','QSQPPRPPRPAANLA','QSRPHQRPSTMPATS','QTYAHSHSYTPTSSQ','RFAPQNNVVSAPTYY','RFLLDEDICPLCHGV','RFYCSKCGNTGYKLK','RGSGRTRFLLDEDIC','RLGGVLCGECRGSGR','RLQSQPPRPPRPAAN','RPAANLAQGHQSRPH','RPHQRPSTMPATSSS','RPLYVQPGDPRLGGV','RPPRPAANLAQGHQS','RPQQNPSLPWTYPPR','RPSTMPATSSSQTYA','RSCKSCWRRFAPQNN','SCKSCWRRFAPQNNV','SCWRRFAPQNNVVSA','SGRTRFLLDEDICPL','SHSYTPTSSQPRPPP','SKCGNTGYKLKNGRS','SLPWTYPPRFYCSKC','SQPPRPPRPAANLAQ','SQPRPPPRPQQNPSL','SQTYAHSHSYTPTSS','SRPHQRPSTMPATSS','SSQTYAHSHSYTPTS','SSSQTYAHSHSYTPT','STMPATSSSQTYAHS','SYEDVIKEEERLQSQ','SYTPTSSQPRPPPRP','TGYKLKNGRSCKSCW','THDDELPSYEDVIKE','TMPVYTNAWQGNRPL','TNAWQGNRPLYVQPG','TNYTMPVYTNAWQGN','TRFLLDEDICPLCHG','TSSQPRPPPRPQQNP','TSSSQTYAHSHSYTP','TYAHSHSYTPTSSQP','TYPPRFYCSKCGNTG','TYYTNYTMPVYTNAW','VIKEEERLQSQPPRP','VQPGDPRLGGVLCGE','VSAPTYYTNYTMPVY','VVSAPTYYTNYTMPV','VYTNAWQGNRPLYVQ','WQGNRPLYVQPGDPR','WTYPPRFYCSKCGNT','YAHSHSYTPTSSQPR','YCSKCGNTGYKLKNG','YEDVIKEEERLQSQP','YKLKNGRSCKSCWRR','YTMPVYTNAWQGNRP','YTNAWQGNRPLYVQP','YTNYTMPVYTNAWQG','LCHGVGRIITQPQRY','YTPTSSQPRPPPRPQ','YVQPGDPRLGGVLCG','YYTNYTMPVYTNAWQ']


###############################
# this part breaks the strings
# and creates a dictionary
###############################
d={}
b={}

N=4
for s in L:
  if s[0:N] not in b:
     b[s[0:N]]=0
  for i in range(0,len(s)-N):
     d[s[i:i+N]]=s[i+N]
     if i>0:
         b[s[i:i+N]]=1

for s in b:
    if b[s]==0:
        begin=s


seq=begin


###############################
# this part adds new elements
###############################
while True:
      if begin in d:
        next=d[begin]
        seq += next
        begin=begin[1:N]+next
      else:
        break

print seq
